image: ruby:2.6

cache:
  paths:
    - vendor/bundle

before_script:
  - export LC_ALL=en_US.UTF-8
  - locale-gen en_US.UTF-8
  - gem install bundler:2.0.1
  - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor/bundle

rubocop:
  script:
    - bundle exec rubocop

rspec:
  script:
    - export LC_ALL=en_US.UTF-8
    - locale-gen en_US.UTF-8
    - bundle exec rspec
  coverage: /LOC \((\d+.\d+)%/
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mkdir -p public/coverage/
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
