image: ruby:2.6-alpine3.9

cache:
  paths:
    - vendor/ruby

before_script:
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rubocop:
  script:
    - rubocop

rspec:
  script:
    - rspec rspec
  coverage: /LOC \((\d+.\d+)%/
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mkdir -p public/coverage/
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
