image: ruby:2.6

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor/bundle

rubocop:
  script:
    - bin/rubocop

rspec:
  script:
    - bin/rspec rspec
  coverage: /LOC \((\d+.\d+)%/
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mkdir -p public/coverage/
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
